add_alarm:
  name: Add alarm
  fields:
    label: { required: true, selector: { text: {} } }
    time: { required: true, selector: { time: {} } }
    days: { selector: { select: { multiple: true, options: ["0","1","2","3","4","5","6"] } } }
    description: { selector: { text: {} } }
    enabled: { selector: { boolean: {} } }
    location: { selector: { area: {} } }
update_alarm:
  name: Update alarm
  fields:
    id: { required: true, selector: { text: {} } }
remove_alarm:
  name: Remove alarm
  fields:
    id: { required: true, selector: { text: {} } }
start_timer:
  name: Start timer
  fields:
    name: { required: true, selector: { text: {} } }
    hours: { selector: { number: { min: 0, max: 23 } } }
    minutes: { selector: { number: { min: 0, max: 59 } } }
    seconds: { selector: { number: { min: 0, max: 59 } } }
    location: { selector: { area: {} } }
cancel_timer:
  name: Cancel timer
  fields:
    id: { required: true, selector: { text: {} } }
pause_timer:
  name: Pause timer
  fields:
    id: { required: true, selector: { text: {} } }
resume_timer:
  name: Resume timer
  fields:
    id: { required: true, selector: { text: {} } }
update_timer:
  name: Update timer
  fields:
    id: { required: true, selector: { text: {} } }
    name: { selector: { text: {} } }
    hours: { selector: { number: { min: 0, max: 23 } } }
    minutes: { selector: { number: { min: 0, max: 59 } } }
    seconds: { selector: { number: { min: 0, max: 59 } } }
